name: Workflow for Codecov coverage
on: [push, pull_request]
jobs:
  coverage_job:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: key_for_converage_secret_psyyyyyy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: |
          coverage run --source='.' manage.py test
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
